#!/bin/zsh
# Voir le CERVEAU forager : planificateur (WM v2) + résidu7, homéostasie ON, multi-pellets.
# Lance : bash voir_cerveau.sh   (depuis la racine du repo ; serveurs 6051/6041 doivent tourner)
cd /home/edgarbrunet/Documents/PERSO/SylvanV1
SYLVAN_CPG=1 SYLVAN_RESIDUAL_GAIN=0.4 SYLVAN_CMD_VX=0.5 SYLVAN_CMD_OMEGA=0 SYLVAN_CPG_PERIOD=0.5 \
SYLVAN_CPG_TURNK=0.6 SYLVAN_CPG_TURNAMP=0 SYLVAN_CPG_PLANNER=1 \
SYLVAN_COLLECT=1 SYLVAN_NUM_EPISODES=20 SYLVAN_MAX_EPISODE_STEPS=1500 SYLVAN_SEED=1 SYLVAN_FOOD_COUNT=6 \
SYLVAN_COLLECTOR_MODE=policy_server SYLVAN_POLICY_HOST=127.0.0.1 SYLVAN_POLICY_PORT=6051 \
SYLVAN_POLICY_EXPLORATION_STD_INITIAL=0 SYLVAN_POLICY_EXPLORATION_STD_FINAL=0 \
SYLVAN_REFLEX_STRENGTH=0 SYLVAN_ASSIST_RATIO=0 \
SYLVAN_RUN_DIR=data/replay_buffer/view \
./tools/godot/godot --path godot
