#!/bin/zsh
# Voir la BASE marcher/tourner (résidu7, sans cerveau). 1er arg = omega (0 = tout droit, 0.6 = tourne).
# Lance : bash scripts/voir_base.sh 0.6   (serveur 6041 doit tourner)
cd /home/edgarbrunet/Documents/PERSO/SylvanV1
OM=${1:-0.6}
SYLVAN_CPG=1 SYLVAN_RESIDUAL_GAIN=0.4 SYLVAN_CMD_VX=0.5 SYLVAN_CMD_OMEGA=$OM SYLVAN_CPG_PERIOD=0.5 \
SYLVAN_CPG_TURNK=0.6 SYLVAN_CPG_TURNAMP=0 \
SYLVAN_COLLECT=1 SYLVAN_NUM_EPISODES=20 SYLVAN_MAX_EPISODE_STEPS=600 SYLVAN_SEED=1 SYLVAN_DISABLE_HOMEOSTASIS=1 \
SYLVAN_COLLECTOR_MODE=policy_server SYLVAN_POLICY_HOST=127.0.0.1 SYLVAN_POLICY_PORT=6041 \
SYLVAN_POLICY_EXPLORATION_STD_INITIAL=0 SYLVAN_POLICY_EXPLORATION_STD_FINAL=0 \
SYLVAN_REFLEX_STRENGTH=0 SYLVAN_ASSIST_RATIO=0 \
SYLVAN_RUN_DIR=data/replay_buffer/view \
./tools/godot/godot --path godot
